[package]
name = "day4"
version = "0.1.0"
authors = ["Ryan Bluth <ryanbluth93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.7"
regex = "1.1.7"
lazy_static = "1.3.0"